# Generated by Django 2.2 on 2019-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
